### ISSUE TITLE
[BUG]:Impossible to add User ID to Task

### ISSUE THREAD

**Issue by mocktarissa** [hngi/fury-backend-python#20]
**When Posting to v1/task User Id gets NOT NULL constraint failed: task_task.owner_id and returns 500 internal server Error **

**To Reproduce**
1. Post  to '/v1/task'
2. Scroll down to logs'
3. See error

**Expected behavior**
Return 201
**Screenshots**
![image](https://user-images.githubusercontent.com/44744049/84465951-ee2ded00-ac80-11ea-9bcc-e938f48e0aa1.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version ?

**Comment by AjibsBaba** [comment]
The bug has been fixed and a pull request has been created
