### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by Arch997** [hngi/fury-backend-python#3]
• What documentation tool have we settled on?

• List out API endpoints to be used in this service.

• Each endpoint request data must be validated to show it works. The core is based on PUT, DELETE, GET, POST

**Comment by Fortunate245** [comment]
OK @Arch997 I will be in touch....... When are we to submit this?

**Comment by Kamikaze49** [comment]
I thought we settled on Swagger as the documentation tool

**Comment by Arch997** [comment]
@Kamikaze49  We did. Have you started working on this?

**Comment by jan-far** [comment]
Please, i understand we are working on and endpoint for employee management but i I'm lost. I thought @Arch997 was asking a question when he opened an issue, or are you in charge of this? Do shed more light and as to where one can come in. Thanks 🤗

**Comment by Arch997** [comment]
@jan-far  true. I was asking a question. Perhaps I wasn't clear enough. @Kamikaze49  can you take charge of this. I'm presently writing models for the project

**Comment by Kamikaze49** [comment]
@Arch997 I was working on the readme

**Comment by Fortunate245** [comment]
@Arch997  please I need an update...... Can I dm on slack

**Comment by Arch997** [comment]
Please do
