### ISSUE TITLE
[BUG]:doesn't redirect to /admin when session login is clicked from / route 

### ISSUE THREAD

**Issue by mocktarissa** [hngi/fury-backend-python#30]
**Describe the bug**
Link to admin should be changed in URL 
**To Reproduce**
1. Go to '/'
2. Click on 'Session Login.'
3. See error

**Expected behavior**
Redirects to /admin
**Screenshots**
![image](https://user-images.githubusercontent.com/44744049/84506712-6e2b7580-acc8-11ea-97c1-51489bc543cb.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Comment by everybees** [comment]
I fixed this already.
