### ISSUE TITLE
[DOCS]Build ER diagram for Database

### ISSUE THREAD

**Issue by mocktarissa** [hngi/fury-backend-python#4]
**Give brief description of what documentation changes were made.**

**Comment by Nyior** [comment]
Has been taken care of? If not I could jump on it

**Comment by mocktarissa** [comment]
> Has been taken care of? If not I could jump on it

Go and submit your diagram at: https://docs.google.com/forms/d/e/1FAIpQLSe5AB41WbCr4d93VF--THRLWn-wAOpCuYEx2HN5Y_C7rXPAnQ/viewform?usp=sf_link

**Comment by Nyior** [comment]
I could but I don't have a complete understanding of what the project is about.

**Comment by Hopekodi** [comment]
So for the ER diagram i used lucid chart which has all the tool features

This is the invite link if u want to view the diagram
https://app.lucidchart.com/invitations/accept/7fd8e4b3-ed4d-4556-823d-0e3b3cfb1d01
Note: to view the diagram you have to sign up to lucid chat first,  its not same as lucid).
it has ER features, so all that was done was to create the two tables

then link the primary key to the main table, u have all the symbols

the first table is the table that stores the categories, and the second stores the data for the Tasks

that first symbol implies that the category can be as many as possible, but might not have any task attached to it yet (Many to zero relation), the second image is  1 to 1 relation, this means one task must have one category attached to it.

The image is the relationship between the tasks and the category each task falls to.

**Comment by AnnArinze** [comment]
I am a Python beginner but this task has forced some of us to quickly research APIs and other things so that we can know how to contribute adequately to these tasks.
