### ISSUE TITLE
Reminder Feature

### ISSUE THREAD

**Issue by Arch997** [hngi/fury-backend-python#5]
A reminder feature for the events planned. How do we think this can be implemented?

**Comment by msoladoye** [comment]
@Arch997 since the API is required to be reusable, API token should be considered when the models are being created and also when the API is been called from any app. this was users of the API can be verified as see if they have to any of the methods that will be defined in the API

**Comment by ajadi473** [comment]
> A reminder feature for the events planned. How do we think this can be implemented?

We could use celery to run background tasks
